describe('Testando uma Loja online', () => {
  it('Fazendo Login', () => {
    let infos = criarUsers()
    cy.wait(3000)
    cy.visit("https://demo.opencart.com/en-gb?route=account/login")
    cy.get('#input-email').type(infos[2])
    cy.get('#input-password').type(infos[1])
    cy.get('#form-login > .text-end > .btn').click()
    cy.get('#content > :nth-child(1)').should("contain.text","My Account")
  })
  it('Mudar email', () => {
    let infos = criarUsers()
    cy.wait(3000)
    cy.visit("https://demo.opencart.com/en-gb?route=account/login")
    cy.get('#input-email').type(infos[2])
    cy.get('#input-password').type(infos[1])
    cy.get('#form-login > .text-end > .btn').click()
    cy.wait(2000)
    cy.get('#content > :nth-child(1)').should("contain.text","My Account")
    cy.get('#content > :nth-child(2) > :nth-child(1) > a').click()
    cy.get('#input-email').clear()
    cy.get('#input-email').type(infos[3])
    cy.get('.text-end > .btn').click()
    cy.get('.alert').should("contain.text"," Success: Your account has been successfully updated.")
  })
  it('Mudar Senha ', () => {
    let infos = criarUsers()
    cy.wait(3000)
    cy.visit("https://demo.opencart.com/en-gb?route=account/login")
    cy.get('#input-email').type(infos[2])
    cy.get('#input-password').type(infos[1])
    cy.get('#form-login > .text-end > .btn').click()
    cy.wait(2000)
    cy.get('#content > :nth-child(1)').should("contain.text","My Account")
    cy.get('#content > :nth-child(2) > :nth-child(2) > a').click()
    cy.get('#input-password').type(infos[4])
    cy.get('#input-confirm').type(infos[4])
    cy.get('.text-end > .btn').click()
    cy.get('.alert').should("contain.text","Success: Your password has been successfully updated.")
})
it('Mudar Senha com falha', () => {
  let infos = criarUsers()
  cy.wait(3000)
  cy.visit("https://demo.opencart.com/en-gb?route=account/login")
  cy.get('#input-email').type(infos[2])
  cy.get('#input-password').type(infos[1])
  cy.get('#form-login > .text-end > .btn').click()
  cy.get('#content > :nth-child(1)').should("contain.text","My Account")
  cy.wait(2000)
  cy.get('#content > :nth-child(2) > :nth-child(2) > a').click()
  cy.get('#input-password').type(infos[4])
  cy.get('#input-confirm').type(infos[1])
  cy.get('.text-end > .btn').click()
  cy.get('#error-confirm').should("contain.text","Password confirmation does not match password!")
})
it('Adicionar Iphone ao carrinho', () => {
  let infos = criarUsers()
  cy.wait(3000)
  cy.visit("https://demo.opencart.com/en-gb?route=account/login")
  cy.get('#input-email').type(infos[2])
  cy.get('#input-password').type(infos[1])
  cy.get('#form-login > .text-end > .btn').click()
  cy.get('#content > :nth-child(1)').should("contain.text","My Account")
  cy.get('.breadcrumb > :nth-child(1)').click()
  cy.get(':nth-child(2) > .product-thumb > .content > form > .button-group > [formaction="https://demo.opencart.com/en-gb?route=checkout/cart.add"]').click()
  cy.wait(1000)
  cy.get('.alert').should("contain.text","Success: You have added iPhone to your shopping cart!")

})
it('Adicionar Macbook a wishlist', () => {
  let infos = criarUsers()
  cy.wait(3000)
  cy.visit("https://demo.opencart.com/en-gb?route=account/login")
  cy.get('#input-email').type(infos[2])
  cy.get('#input-password').type(infos[1])
  cy.get('#form-login > .text-end > .btn').click()
  cy.wait(2000)
  cy.get('.fas').click()
  cy.wait(1000)
  cy.get(':nth-child(1) > .product-thumb > .content > form > .button-group > [formaction="https://demo.opencart.com/en-gb?route=account/wishlist.add"]').click()
  cy.get('.alert').should("contain.text","Success: You have added MacBook to your wish list!")
})

})
function criarUsers(){
  let hora = new Date().getHours().toString()
  let minuto =new Date().getMinutes().toString()
  let seg = new Date().getSeconds().toString()
  let Email = minuto + seg +"@gmail.com" 
  let Emailn = minuto + seg + hora +"@gmail.com" 
  let nova_senha = seg+minuto+"a"
  let ID = hora + minuto +seg + "ID"
  let Senha = hora + minuto +seg + "Senha"
  let infos =[ID,Senha,Email,Emailn,nova_senha]
  cy.visit("https://demo.opencart.com/en-gb?route=account/register")
    
  cy.get('#input-firstname').type(infos[0])
  cy.get('#input-lastname').type(infos[0])
  cy.get('#input-password').type(infos[1])
  cy.get('#input-email').type(infos[2])
  cy.get('#input-newsletter').click()
  cy.get('.text-end > .form-check > .form-check-input').click()
  cy.get('.text-end > .btn').click()
  cy.get('h1').should("contain.text","Your Account Has Been Created!")
  cy.get('.text-end > .btn').click() 
      return infos
}